# -*- coding: utf-8 -*-
"""Lemniscate Plot Script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I_ndjEnUUf6ISskqlWQsclkyhjQhUiS3
"""

# -*- coding: utf-8 -*-
#
# Script to generate the conceptual visualization
# of the Lemniscate topology for the Sekala/Niskala Meta-Universe.
#

import numpy as np
import matplotlib.pyplot as plt

def plot_cosmic_cycle():
    """
    Generates and saves a plot of the lemniscate topology with the two spiral galaxies
    representing the Sekala and Niskala universes.
    """
    # --- Lemniscate Parameters (Cosmic Cycle) ---
    theta = np.linspace(-np.pi/4, np.pi/4, 500)
    a = 2.5
    r_pos = a * np.sqrt(np.cos(2 * theta))
    r_neg = -a * np.sqrt(np.cos(2 * theta))

    # Cartesian Coordinates
    x_pos = r_pos * np.cos(theta)
    y_pos = r_pos * np.sin(theta)

    x_neg = r_neg * np.cos(theta + np.pi)
    y_neg = r_neg * np.sin(theta + np.pi)

    # --- Spiral Galaxy Parameters ---
    theta_spiral = np.linspace(0, 4 * np.pi, 200)
    k = 0.2  # Winding factor

    # Sekala Galaxy (green)
    r_spiral1 = k * theta_spiral
    x_spiral1 = r_spiral1 * np.cos(theta_spiral) + a/2
    y_spiral1 = r_spiral1 * np.sin(theta_spiral)

    # Niskala Galaxy (red, opposite)
    r_spiral2 = k * theta_spiral
    x_spiral2 = -r_spiral2 * np.cos(-theta_spiral) - a/2
    y_spiral2 = r_spiral2 * np.sin(-theta_spiral)

    # --- Figure Creation ---
    plt.style.use('seaborn-v0_8-whitegrid')
    fig, ax = plt.subplots(figsize=(10, 8))

    # Plot cosmic cycle
    ax.plot(x_pos, y_pos, color='deepskyblue', lw=2, label='Sekala Branch (Matter)')
    ax.plot(x_neg, y_neg, color='orangered', lw=2, label='Niskala Branch (Antimatter)')

    # Plot galaxies
    ax.plot(x_spiral1, y_spiral1, 'g-', label='Sekala Galaxy (Unfurl)')
    ax.plot(x_spiral2, y_spiral2, 'r-', label='Niskala Galaxy (Enfold)')

    # Chart Settings
    ax.set_title('Sekala/Niskala: The Woven Cosmos Topology', fontsize=16)
    ax.set_xlabel('Spatial Dimension', fontsize=12)
    ax.set_ylabel('Spatial Dimension', fontsize=12)
    ax.legend()
    ax.axis('equal')
    ax.grid(True, linestyle='--', alpha=0.6)

    # Save the figure
    plt.savefig("lemniscate_cosmic_cycle.png", dpi=300, bbox_inches='tight')
    print("Plot saved as 'lemniscate_cosmic_cycle.png'")
    plt.show()

if __name__ == '__main__':
    plot_cosmic_cycle()